version: 2.1.{build}

branches:
# whitelist
    only:
        - master
        - appveyor

install:
    - git submodule -q update --init

before_build:
    - mkdir projects\build
    - cd projects\build
    - cmake -G"Visual Studio 12" -T"v120" -B. ..\CMake\
    - cd ..\..

build:
    project: projects\build\rxcpp.sln

artifacts:
  - path: Rx\v2\src\
    name: rxcpp source
    type: zip
  - path: Rx\v2\examples\
    name: rxcpp examples
    type: zip

  - provider: Slack
    auth_token: 
      secure: qaGjbI98VXZa7Zd2s3RmMzfA+ymrfWUDuzevdtOcHssEGBXbcoOJzLHNOmG+Y1nX
    channel: rxcpp